repos:
  # lint code using ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff-format # formatter
        types_or: [python, pyi, jupyter, toml]
      - id: ruff # linter
        types_or: [python, pyi, jupyter, toml]
        args: [--fix]
