general:
    seed: 42
    root_dir: "graph-pes-results"
    log_level: "INFO"

fitting:
    pre_fit_model: true
    max_n_pre_fit: 5_000
    early_stopping_patience: 100

    optimizer:
        graph_pes.training.opt.Optimizer:
            name: AdamW
            lr: 0.001
            weight_decay: 0.0
            amsgrad: false

    # no scheduler enabled by default
    scheduler: null

    # train for 100 epochs on the best device available
    trainer_kwargs:
        max_epochs: 100
        accelerator: auto
        enable_model_summary: false

    loader_kwargs:
        num_workers: 0
        persistent_workers: false
        batch_size: 4
        pin_memory: false

wandb: {}
