general:
    seed: 42
    root_dir: "graph-pes-results"
    run_id: null
    log_level: "INFO"
    progress: rich
    torch:
        dtype: float32
        float32_matmul_precision: high

fitting:
    pre_fit_model: true
    max_n_pre_fit: 5_000

    # train for 100 epochs on the best device available
    trainer_kwargs:
        max_epochs: 100
        accelerator: auto
        enable_model_summary: false

    loader_kwargs:
        num_workers: 1
        persistent_workers: true
        batch_size: 4
        pin_memory: false

    # "fancy"/optional training options disabled
    callbacks: []
    scheduler: null
    swa: null
    early_stopping: null
    auto_fit_reference_energies: false

    # this is deprecated, use `early_stopping` instead
    early_stopping_patience: null

wandb: {}
